### PR TITLE
Bugfix/authentication expiration not handled

### PR DESCRIPTION
**Pull request by baywet**
implemented multiple improvements to the way discovery and authentication as well as authentication exceptions are handled. 
Cancelling #38 as it includes it as well

### CODE REVIEW

**Comment by baywet** [comment]
fixes #37

**Comment by baywet** [comment]
thanks for the merge @kenakamu QQ: when do you think you will publish the nuget? is that automated yet?

**Comment by kenakamu** [comment]
Published. Not automation (yet) but do we want to automate this for every check-in?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by baywet** [comment]
thanks!
every pull request (or PR update) would trigger build + unit tests.
every merge to master would trigger build + unit test + release.
however I think we should have like a pre-approval on the release definition (to speak in VSTS terms) to allow you to approve or not something getting to nuget. What do you think?

**Comment by kenakamu** [comment]
Sounds great but we don't have unit test ?

**Comment by baywet** [comment]
I know but we could set up the infrastructure for it, have a few basic unit tests and build up from there. 
I'm going to move those discussions to separate threads:
- Continuous integration
- Continuous publishing + approval
- Unit tests

**Pull request merged**
